name: middleware
description: SILLAENC Parking Backend System Made by BJS.
version: 0.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.1

# Add regular dependencies here.
dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_body_parser: ^3.1.0
  sqlite3: ^2.4.2
  http: ^1.2.1
  fluro: ^2.0.5
  http_parser: ^4.0.2

dev_dependencies:
  build_runner: ^2.1.4
  shelf_router_generator: ^1.1.0